# Generated by Django 3.2.25 on 2024-10-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_shippingcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcharge',
            name='type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
