# Generated by Django 3.2.7 on 2021-10-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20211005_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productZone',
        ),
    ]
