# Generated by Django 3.2.25 on 2025-03-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variety',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
