# Generated by Django 3.2.7 on 2021-10-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_product_pack_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pack_size',
        ),
    ]
