# Generated by Django 3.2.7 on 2022-01-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_cart_cartproduct_favourite_orderapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumb_image',
            field=models.FileField(blank=True, null=True, upload_to='thumbs', verbose_name='product_thumbnail'),
        ),
    ]
