# Generated by Django 3.2.7 on 2022-01-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_category_thumb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='packsize',
            name='measure',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='packsize',
            name='qty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
