# Generated by Django 3.2.12 on 2022-05-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_orderapp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='remark',
            field=models.CharField(blank=True, max_length=258, null=True),
        ),
    ]
