# Generated by Django 3.2.8 on 2024-05-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='distributor_slab',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
